//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGZY.WebUI.admin.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YH_LOCN
    {
        public Nullable<System.DateTime> SYSDATE { get; set; }
        public string WHSE { get; set; }
        public string ZONE { get; set; }
        public string LOCN_CLASS { get; set; }
        public string LOCN_BRCD { get; set; }
        public string SEASON { get; set; }
        public string HZ { get; set; }
        public string SKU_ID { get; set; }
        public string SIZE_DESC { get; set; }
        public string SKU_BRCD { get; set; }
        public string SKU_DESC { get; set; }
        public string COLOR { get; set; }
        public Nullable<decimal> STD_PACK_QTY { get; set; }
        public string UOM { get; set; }
        public string 生产厂家 { get; set; }
        public string C_APPR_CODE { get; set; }
        public string C_QSTD { get; set; }
        public string CC { get; set; }
        public string BATCH_NBR { get; set; }
        public Nullable<double> ACTL_INVN_QTY { get; set; }
        public Nullable<System.DateTime> XPIRE_DATE { get; set; }
        public string 剂型 { get; set; }
        public string IMPORT { get; set; }
        public string SPL_INSTR_CODE_9 { get; set; }
        public string SPL_INSTR_CODE_10 { get; set; }
        public string C_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE_TIME { get; set; }
        public Nullable<double> ROWNUM_ORDER { get; set; }
        public int id { get; set; }
    }
}
